apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "gatekeeper-app.labels" . | indent 4 }}
  name: gatekeeper-controller-manager-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app.kubernetes.io/name: {{ include "gatekeeper-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}