apiVersion: v1
kind: Service
metadata:
  labels:
    app: '{{ template "gatekeeper-app.name" . }}'
    chart: '{{ template "gatekeeper-app.name" . }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
{{ include "gatekeeper-app.labels" . | indent 4 }}
  name: gatekeeper-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: '{{ template "gatekeeper-app.name" . }}'
    chart: '{{ template "gatekeeper-app.name" . }}'
    control-plane: controller-manager
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
