version: 2.1
orbs:
  architect: giantswarm/architect@2.7.0

workflows:
  build-and-push:
    jobs:
      - architect/push-to-app-catalog:
          name: push-gatekeeper-app-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "gatekeeper-app"
          filters:
            # Trigger job on git tag.
            tags:
              only: /^v.*/
