version: 2.1
orbs:
  architect: giantswarm/architect@0.10.0

workflows:
  build-and-push:
    jobs:
      - architect/push-to-app-catalog:
          name: push-gatekeeper-app-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "gatekeeper-app"
          filters:
            # Trigger job on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-gatekeeper-app-to-aws-app-collection
          app_name: "gatekeeper-app"
          app_collection_repo: "aws-app-collection"
          unique: "true"
          requires:
            - push-gatekeeper-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-gatekeeper-app-to-azure-app-collection
          app_name: "gatekeeper-app"
          app_collection_repo: "azure-app-collection"
          unique: "true"
          requires:
            - push-gatekeeper-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-gatekeeper-app-to-kvm-app-collection
          app_name: "gatekeeper-app"
          app_collection_repo: "kvm-app-collection"
          unique: "true"
          requires:
            - push-gatekeeper-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
