# Default values for gatekeeper-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

crds: 
  enabled: true

image:
  repository: quay.io/open-policy-agent/gatekeeper
  tag: v3.1.0-beta.4
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

replicas: 1
auditInterval: 60
constraintViolationsLimit: 20

nodeSelector: {}

tolerations: []

affinity: {}
