replicas: 1
auditInterval: 60
constraintViolationsLimit: 20
auditFromCache: false
logLevel: INFO
image:
  name: giantswarm/gatekeeper
  release: v3.1.0-beta.8
  pullPolicy: IfNotPresent
nodeSelector: {}
tolerations: []
podAnnotations: {}
resources:
  requests:
    cpu: 100m
    memory: 256Mi
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
Installation:
  V1:
    Registry:
      Domain: quay.io
